### ISSUE TITLE
Unexpected token '.' composer.js:33 when launching main or staging

### ISSUE THREAD

**Issue by FreezyExp** [BlueprintCoding/SillyTavernSimpleLauncher#23]
Seems like my setup is somehow incorrect, I already tried clearing the venv and reinstalling.
Any ideas on how to resolve this issue?

SillyTavern-DevBranch\node_modules\yaml\dist\compose\composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\SillyTavern-DevBranch\node_modules\yaml\dist\index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code 1
npm ERR! path C:\SillyTavern-DevBranch
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node post-install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Freezy\AppData\Local\npm-cache\_logs\2024-01-17T09_36_46_678Z-debug.log
C:\SillyTavern-DevBranch\node_modules\signal-exit\dist\cjs\index.js:162
        const ev = opts?.alwaysLast ? 'afterExit' : 'exit';
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\SillyTavern-DevBranch\node_modules\write-file-atomic\lib\index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Press any key to continue . . .

**Comment by FreezyExp** [comment]
Seems like old version of node or npm, uninstalling node & npm and reinstalling those.
Installed NVM then use 'nvm on' to switch to the latest version.

That helped :P perhaps checking the version and adding that as information "npm version >=X required" vitis <link> for instructions
